name: "\U0001F41E Bug report"
description: Report a reproducible bug in Sandbooks
title: "[Bug]: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report. Please provide as much detail as possible so we can reproduce and fix the issue quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: "Code blocks fail to execute when..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the exact steps so we can reproduce the problem.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Code executes and returns output..."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Received 500 response..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Include OS, browser, version, and whether you're using production or local development."
      placeholder: "macOS 14.5, Chrome 129, production"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs & screenshots
      description: Attach terminal logs, network traces, or screenshots/gif if available.
      render: bash
  - type: checkboxes
    id: safeguards
    attributes:
      label: Safeguards
      options:
        - label: I have searched existing issues
          required: true
        - label: I can reproduce this with the latest main branch
          required: false
